Io pattern
filecoin-project/neptune pull request #157
Opened 2022-08-03 00:30 UTC by porcuquine

This PR renames `SpongeParameter::OpSequence` to `IOPattern` and enforces the specific pattern committed to at runtime. However, alternate equivalent patterns (after coalescing runs of absorb/squeeze ops) are still have the same tag so are compatible. This allows alternate implementations to enjoy runtime safety (checked against declared pattern) while still allowing freedom to chunk operations as desired. These changes bring the Sponge API implementation in sync with the spec (https://hackmd.io/bHgsH6mMStCVibM_wYvb2w) in its current state.

2022-08-03 13:27 UTC, veorq approved these changes

2022-08-03 13:28 UTC, veorq requested changes
As discussed, hasher update in absorb() and squeeze() seems superfluous wrt the specs

2022-08-03 17:32 UTC, veorq approved these changes

2022-08-04 15:58 UTC, emmorais approved these changes

2022-08-08 16:26 UTC, merged