Port `calc_round_numbers.py` to rust
filecoin-project/neptune pull request #81
Opened 2021-01-25 02:05 UTC by DrPeterVanNostrand

2021-02-08 21:59 UTC, porcuquine requested changes
Looks good. Thanks for doing this. I think it's worth making the small change I noted in a comment, then we can merge.

2021-02-08 21:59 UTC, porcuquine commented on src/lib.rs
> +        _ => return calc_round_numbers(width, true),
I think we could just move the historical hard-coded values to a unit test (to ensure consistency), then always calculate here.

2021-02-18 21:47 UTC, porcuquine commented
And looks like it needs a rebase.

2021-03-08 21:49 UTC, porcuquine commented
@DrPeterVanNostrand Can you just update comments to remove the TODO requesting support for an odd number of full rounds, as discussed in the issue? https://github.com/filecoin-project/neptune/issues/83#issuecomment-789249291

2021-03-10 23:48 UTC, porcuquine approved these changes
LGTM. Just needs a rebase (and possibly one more small comment adjustment, as noted0.

2021-03-10 23:48 UTC, porcuquine commented on src/round_numbers.rs
> +// the function `calc_round_numbers_strengthened()`.
This says 'does not indicate' — but I think it *does* indicate that. I think maybe this comment is out of date, since I don't see `calc_round_numbers_strengthened()` at all.

2021-03-11 19:54 UTC, DrPeterVanNostrand commented on src/round_numbers.rs
> +// the function `calc_round_numbers_strengthened()`.
I believe using round numbers with a "security margin" (where you increase the round numbers using: `R_F += 2`, `R_P *= 1.075`) is different than using "strengthened" round numbers (`R_P *= 1.25`). `calc_round_numbers.py` always uses a security margin, which is why `security_margin` is set to `true` in the Rust version [here](https://github.com/filecoin-project/neptune/blob/round-constants/src/lib.rs#L95).

2021-03-11 19:55 UTC, DrPeterVanNostrand commented on src/round_numbers.rs
> +// the function `calc_round_numbers_strengthened()`.
"Security margin" is given in section 5.4 of the [Poseidon paper](https://eprint.iacr.org/2019/458.pdf)

2021-03-11 20:01 UTC, DrPeterVanNostrand commented on src/round_numbers.rs
> +// the function `calc_round_numbers_strengthened()`.
I did have a type in the comment `calc_round_numbers_strengthened()` -> `round_numbers_strengthened()`

2021-03-11 20:42 UTC, porcuquine commented on src/round_numbers.rs
> +// the function `calc_round_numbers_strengthened()`.
Okay,  I get it. Thanks for the clarification.

2021-03-11 20:42 UTC, merged