Add spec document.
filecoin-project/neptune pull request #84
Opened 2021-03-02 21:18 UTC by DrPeterVanNostrand

2021-03-11 22:45 UTC, porcuquine approved these changes
This looks really good. I made a few minor comments.

2021-03-11 22:45 UTC, porcuquine commented on spec/spec.md
> +
Why use \oplus for field addition? I think that usually means xor or direct sum. It seems like this is just vector addition of field elements. Maybe that's fine, given that you're using linear algebra operations with field elements elsewhere, without extra notation.

2021-03-11 22:45 UTC, porcuquine commented on spec/spec.md
> +Returns the value of matrix $m$ at row $i$ column $j$.
Strongly consider capitalizing matrix names throughout, to follow general convention.

2021-03-11 22:45 UTC, porcuquine commented on spec/spec.md
> +Vector-matrix multiplication where vector $v$ is a row vector, $m$ is a matrix, and $\len(v) = \textbf{rows}(m)$. The product is a row vector whose length is equal to the number of columns of $m$. Th
Consider **bold** for vectors, to follow common convention.

2021-03-11 22:45 UTC, porcuquine commented on spec/spec.md
> +Exponentiation in $\Zp$ of a field element $x$ to a positive integer power $\alpha \typecolon \mathbb{Z}_{\geq 0} \hso$.
Should this be 'non-negative' rather than 'positive'? That would make sense and agree with the symbol in the subscript.

2021-03-11 22:45 UTC, porcuquine commented on spec/spec.md
> +$t = \text{preimage length} + \text{output length} = \text{preimage length} + 1 = \Arity + 1$
Although this happens to be true in our case, I don't think it is by definition. I think what you're labeling as 'output length' is actually 'capacity'. If we wanted 256-bit security, then it would be 2 — even though the output length would still be 1.

2021-03-11 22:45 UTC, porcuquine commented on spec/spec.md
> +For each round excluding the last $r \in [R - 1]$, $\RC'_r$ is added to the Poseidon $\state$ after taht round's S-box has been applied.
'taht' -> 'that'

2021-03-11 22:47 UTC, porcuquine requested changes
Whoops. I actually intended to make this review in the `specs` repo. Let's finalize the work there and get it merged, then import any changes here and refer directly to spec rather than to personal HackMD page.

2021-03-13 18:05 UTC, DrPeterVanNostrand commented on spec/spec.md
> +Exponentiation in $\Zp$ of a field element $x$ to a positive integer power $\alpha \typecolon \mathbb{Z}_{\geq 0} \hso$.
Yup, maybe it should just be "integer" and `\mathbb{Z}` because Poseidon allows alpha to be  -1.

2021-03-14 16:20 UTC, DrPeterVanNostrand commented on spec/spec.md
> +Returns the value of matrix $m$ at row $i$ column $j$.
I didn't use capital "M" because it is a reserved symbol in Poseidon. But, I can make it a capital letter

2021-03-16 14:17 UTC, DrPeterVanNostrand commented on spec/spec.md
> +
I used \vec+ and \vec\oplus because I think that it's confusing when + is overloaded to mean multiple things, e.g. real addition, field addition, and/or vector addition simultaneously, so I used + for real addition, \oplus for field addition, and \vec+ and \vec\oplus for vector [field] addition. I could change XOR \oplus_xor to \veebar to disambiguate field addition  \oplus from XOR \oplus_xor.

> direct sum

The SDR spec used direct products \times rather than direct sums \oplus, and neither are used in this doc, so I didn't consider that collision \oplus.

> you're using linear algebra operations with field elements elsewhere, without extra notation

Yea, I didn't think about that. I just wanted to use the non-standard symbol \times to denote matrix-matrix multiplication to aid psuedocode readability. I could specify in the \times's operator description that it occurs between matrices of field elements, and that matrix-matrix multiplication is using the multiplicative subgroup operation.

2021-03-16 15:52 UTC, porcuquine commented on spec/spec.md
> +
I think it's fine however you want to do it. These were just my comments as I read through it the first time. By the time I finished, I understood it, so if on reflection you don't want to change anything, I think it's consistent enough.

2021-04-01 20:14 UTC, closed without merging